### ISSUE TITLE
.NETCORE migration?

### ISSUE THREAD

**Issue by NicoCG** [KirbyMcKenzie/BuddyBot#19]
@KirbyMcKenzie nice little project you have here! any thoughts on migrating to dotnetcore?

**Comment by KirbyMcKenzie** [comment]
Hey @NicoCG, thanks! Migrating to .NET core would be advantageous as that's where all the new shiny features will be, but moving the Bot Builder SDK from v3 to v4 would require a pretty significant re-write to the bot code, so no plans at this stage.
